### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by vshabanov**
Hi, I've rewrote parser to make it more performant (20-50MB/s, about 10x times faster than Attoparsec). I've also rewrote serializer so it round-trips with tokenizer.

All previous tests pass (except `"eof\\"` is not a non-standard `[Ident "eof\xfffd"]` but `[Ident "eof", Delim '\\']`). New tests related to serialization round-trip added.

`BadUrl`, `BadString` constructor arguments were removed since it's impossible to serialize them in round-trip fashion. Quote type is removed from `String` for the same reason.

Result of `tokenize` is just `[Token]`, not `Either` since parser never fails.

New parser is also incremental (starts returning results immediately and does not keep whole list in memory if it's not necessary, thanks to `inlineInterleaveST`).

And I've cherry picked your benchmark commit from another branch and added few more benchmarks.

For the last week it's running in production in [BazQux Reader](https://bazqux.com) with no crashes (new parser uses some unsafe array access).

Thank you for writing this library. It helped me to sanitize bad styles (like removing position:fixed ads) and to release a big new feature (responsive website which requires preprocessing articles to make them responsive too). I found it to be slow on some articles and decided to optimize it.

### CODE REVIEW

**Comment by wereHamster** [comment]
First of all, I'm glad that somebody actually uses the library. I wrote it a long time ago and have not used it personally since.

Regarding `BadUrl`, `BadString` and `String`, I think it's unfortunate that it's no longer recover the original input string. It would be useful for debugging for example. Can you quickly explain why it's not possible to serialize them?

As soon as I saw `inlineInterleaveST` I thought "oh god" and pretty much gave up understanding the code. It's like black magic to me. But we have tests, and if the tests pass then everything is good 😊

For future reference, it would be good to also integrate this test suite: https://github.com/SimonSapin/css-parsing-tests. It is used by multiple css-syntax implementations and is likely much more comprehensive than what I wrote (I think I copied the test strings from chromium).

Regarding the kind of processing you do (remove position:fixed), that would be much better done on a higher level than tokens. The css-syntax spec also defines a parsing step (parsing tokens into stylesheets, rules, declaration blocks etc). Removing declarations would be more natural on that level (see https://drafts.csswg.org/css-syntax/#declaration-diagram).

**Comment by wereHamster** [comment]
Oh, another thing. Do you have any notes for future developers which parts of the code they could improve, and possible approaches? For example if you know that a certain function is a known bottleneck in the benchmarks. It would be useful to write these things down, either here as a comment or add to the readme. Thanks.

**Comment by vshabanov** [comment]
> Regarding `BadUrl`, `BadString` and `String`, I think it's unfortunate that it's no longer recover the original input string. It would be useful for debugging for example. Can you quickly explain why it's not possible to serialize them?

You could make `BadUrl "http://good.url.com"` and it's impossible to serialize it in such way that it will parse back as `BadUrl`. Plus there are no arguments in `<bad-url-token>` and `<bad-string-token>` in spec. Spec also says to always serialize `String` with `"` quotes (and do not escape `'` character) so there is no quote type parameter to `String`.
 
For debugging I think it's better to provide error locations. Perhaps it's even possible to parametrize `tokenize` with function to return locations and then inline it with no-op function to get effective tokenizer without locations.

> As soon as I saw `inlineInterleaveST` I thought "oh god" and pretty much gave up understanding the code. It's like black magic to me. But we have tests, and if the tests pass then everything is good 😊

It's just a way to return list element and run next part of `ST` computation when next list element is requested instead of running till the end collecting results in accumulator. `inlineInterleaveST` of course requires you to not modify what was already given out as a pure value.

> For future reference, it would be good to also integrate this test suite: https://github.com/SimonSapin/css-parsing-tests. It is used by multiple css-syntax implementations and is likely much more comprehensive than what I wrote (I think I copied the test strings from chromium).

These are more high level tests. Declarations, not tokenizer.

> Regarding the kind of processing you do (remove position:fixed), that would be much better done on a higher level than tokens. The css-syntax spec also defines a parsing step (parsing tokens into stylesheets, rules, declaration blocks etc). Removing declarations would be more natural on that level (see https://drafts.csswg.org/css-syntax/#declaration-diagram).

Yes, I've seen it but not yet implemented (I'm just collecting `ident whitespace* : (not ';')* ;` and stripping whitespaces/!important, didn't know about `{ [ ... ] }` in declarations and still not sure that they could exists in `style` attribute, but it seems that they need to be correctly skipped at least).

I also think that it's good idea to include declaration-list parser (and to test if with `css-parsing-tests`). Just have no time yet (already spent a bit too much time on optimization, it's addictive ;).

> Oh, another thing. Do you have any notes for future developers which parts of the code they could improve, and possible approaches? For example if you know that a certain function is a known bottleneck in the benchmarks. It would be useful to write these things down, either here as a comment or add to the readme. Thanks.

It's quite fast already. Perhaps it's possible to rewrite serialization to work on buffers directly (bad that `Data.Text.Internal.Builder.writeAtMost` is not exported, `render*` functions could use it instead of creating new `Text` value just to copy it to buffer), but I'm not sure that it will be significantly faster than current `Text.Lazy.Builder` version.

Slowest part at the moment is creating `Token` values list itself. So `"a:1;b:2;"` parses longer than `"aaaa:1111"` since it has more tokens. It don't think we can do much here. Comments/whitespaces are skipped at about 300-400MB/s.

And `preprocessInputStream` could be removed by changing `isWhitespace` and `escapedCodePoint` and maybe few more places.

**Comment by wereHamster** [comment]
Thanks for the explanations. I'll merge this soon and release as v0.1.0.0 to hackage.

You're right about css-parsing-tests only testing the parsing, not tokenization.

I'll have to read more about `inlineInterleaveST`. I thought this would not be necessary in a lazy language.

**Comment by wereHamster** [comment]
I just uploaded the package: http://hackage.haskell.org/package/css-syntax-0.1.0.0. Many thanks for your contribution.

**Comment by vshabanov** [comment]
Great. Thank you!

> I'll have to read more about `inlineInterleaveST`. I thought this would not be necessary in a lazy language.

It's needed precisely because of lazy evaluation. It allows you to run next part of imperative computation when lazy thunk is evaluated. `getContents` is internally implemented via `unsafeInterleaveIO` and allows you to read file contents lazily. Current parser implemented same way as `getContents` -- it tokenizes lazily (which also allows you to not keep whole tokens list in memory and increases performance by making less load on garbage collector).

**Pull request merged**
